name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ennuicastr:latest .

      - name: Archive Code
        run: |
          zip -r ennuicastr-server.zip . -x ".git/*" -x ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Release v${{ github.run_number }}"
          draft: false
          prerelease: false
          files: ennuicastr-server.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
